/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface VotingTokenInterface extends Interface {
    getFunction(nameOrSignature: "accumulatedFees" | "admin" | "allowance" | "allowances" | "approve" | "balanceOf" | "balances" | "burnAccumulatedFees" | "buy" | "endVoting" | "hasVoted" | "lastBurnTime" | "proposedPrices" | "sell" | "setBuyFee" | "setSellFee" | "startVoting" | "timeToVote" | "tokenPrice" | "totalSupply" | "transfer" | "transferFrom" | "upgradeTo" | "vote" | "votes" | "votingActive" | "votingNumber" | "votingStartedTime"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminChanged" | "Approval" | "Transfer" | "Upgraded" | "VotingEnded" | "VotingStarted"): EventFragment;

    encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'allowances', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'balances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'burnAccumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'buy', values?: undefined): string;
encodeFunctionData(functionFragment: 'endVoting', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'lastBurnTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposedPrices', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sell', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setBuyFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setSellFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'startVoting', values?: undefined): string;
encodeFunctionData(functionFragment: 'timeToVote', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'upgradeTo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'votes', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'votingActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'votingNumber', values?: undefined): string;
encodeFunctionData(functionFragment: 'votingStartedTime', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnAccumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastBurnTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposedPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBuyFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSellFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'timeToVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingNumber', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingStartedTime', data: BytesLike): Result;
  }

  
    export namespace AdminChangedEvent {
      export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
      export type OutputTuple = [previousAdmin: string, newAdmin: string];
      export interface OutputObject {previousAdmin: string, newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalEvent {
      export type InputTuple = [_owner: AddressLike, _spender: AddressLike, _value: BigNumberish];
      export type OutputTuple = [_owner: string, _spender: string, _value: bigint];
      export interface OutputObject {_owner: string, _spender: string, _value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [_from: AddressLike, _to: AddressLike, _value: BigNumberish];
      export type OutputTuple = [_from: string, _to: string, _value: bigint];
      export interface OutputObject {_from: string, _to: string, _value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [previousImplementation: AddressLike, newImplementation: AddressLike];
      export type OutputTuple = [previousImplementation: string, newImplementation: string];
      export interface OutputObject {previousImplementation: string, newImplementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotingEndedEvent {
      export type InputTuple = [votingNumber: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [votingNumber: bigint, endTime: bigint];
      export interface OutputObject {votingNumber: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotingStartedEvent {
      export type InputTuple = [votingNumber: BigNumberish, startTime: BigNumberish];
      export type OutputTuple = [votingNumber: bigint, startTime: bigint];
      export interface OutputObject {votingNumber: bigint, startTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VotingToken extends BaseContract {
    
    connect(runner?: ContractRunner | null): VotingToken;
    waitForDeployment(): Promise<this>;

    interface: VotingTokenInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    accumulatedFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [_owner: AddressLike, _spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    allowances: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [_spender: AddressLike, _value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    balances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    burnAccumulatedFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    buy: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    endVoting: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    lastBurnTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposedPrices: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    sell: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setBuyFee: TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setSellFee: TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    startVoting: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    timeToVote: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tokenPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    upgradeTo: TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    votes: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    votingActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    votingNumber: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    votingStartedTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [_owner: AddressLike, _spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowances'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [_spender: AddressLike, _value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'burnAccumulatedFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'endVoting'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastBurnTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposedPrices'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'sell'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBuyFee'): TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSellFee'): TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startVoting'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'timeToVote'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeTo'): TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votes'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'votingActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'votingNumber'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'votingStartedTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'AdminChanged'): TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
getEvent(key: 'VotingEnded'): TypedContractEvent<VotingEndedEvent.InputTuple, VotingEndedEvent.OutputTuple, VotingEndedEvent.OutputObject>;
getEvent(key: 'VotingStarted'): TypedContractEvent<VotingStartedEvent.InputTuple, VotingStartedEvent.OutputTuple, VotingStartedEvent.OutputObject>;

    filters: {
      
      'AdminChanged(address,address)': TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
      AdminChanged: TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
    

      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Upgraded(address,address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    

      'VotingEnded(uint256,uint256)': TypedContractEvent<VotingEndedEvent.InputTuple, VotingEndedEvent.OutputTuple, VotingEndedEvent.OutputObject>;
      VotingEnded: TypedContractEvent<VotingEndedEvent.InputTuple, VotingEndedEvent.OutputTuple, VotingEndedEvent.OutputObject>;
    

      'VotingStarted(uint256,uint256)': TypedContractEvent<VotingStartedEvent.InputTuple, VotingStartedEvent.OutputTuple, VotingStartedEvent.OutputObject>;
      VotingStarted: TypedContractEvent<VotingStartedEvent.InputTuple, VotingStartedEvent.OutputTuple, VotingStartedEvent.OutputObject>;
    
    };
  }