/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as votingTokenTestUpgradeableSol from './VotingTokenTest _Upgradeable.sol/index.js';
export type { votingTokenTestUpgradeableSol };
import type * as votingTokenTestSol from './VotingTokenTest.sol/index.js';
export type { votingTokenTestSol };