/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as votingTokenTestSol from './VotingTokenTest.sol/index.js';
export type { votingTokenTestSol };