/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as votingTokenTestUpgradeableSol from './VotingTokenTest _Upgradeable.sol/index.js';
export * as votingTokenTestSol from './VotingTokenTest.sol/index.js';