/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'Initializable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Initializable__factory>
getContractFactory(name: 'VotingTokenTest_Upgradeable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VotingTokenTest_Upgradeable__factory>
getContractFactory(name: 'VotingTokenTest', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VotingTokenTest__factory>
getContractFactory(name: 'VotingToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VotingToken__factory>
getContractFactory(name: 'Proxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Proxy__factory>
getContractFactory(name: 'VotingToken_Upgradeable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VotingToken_Upgradeable__factory>
getContractFactory(name: 'VotingToken_UUPSproxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VotingToken_UUPSproxy__factory>

  getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'Initializable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Initializable>
getContractAt(name: 'VotingTokenTest_Upgradeable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VotingTokenTest_Upgradeable>
getContractAt(name: 'VotingTokenTest', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VotingTokenTest>
getContractAt(name: 'VotingToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VotingToken>
getContractAt(name: 'Proxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Proxy>
getContractAt(name: 'VotingToken_Upgradeable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VotingToken_Upgradeable>
getContractAt(name: 'VotingToken_UUPSproxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VotingToken_UUPSproxy>

  deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'Initializable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Initializable>
deployContract(name: 'VotingTokenTest_Upgradeable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingTokenTest_Upgradeable>
deployContract(name: 'VotingTokenTest', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingTokenTest>
deployContract(name: 'VotingToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingToken>
deployContract(name: 'Proxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Proxy>
deployContract(name: 'VotingToken_Upgradeable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingToken_Upgradeable>
deployContract(name: 'VotingToken_UUPSproxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingToken_UUPSproxy>

  deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'Initializable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Initializable>
deployContract(name: 'VotingTokenTest_Upgradeable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingTokenTest_Upgradeable>
deployContract(name: 'VotingTokenTest', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingTokenTest>
deployContract(name: 'VotingToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingToken>
deployContract(name: 'Proxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Proxy>
deployContract(name: 'VotingToken_Upgradeable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingToken_Upgradeable>
deployContract(name: 'VotingToken_UUPSproxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VotingToken_UUPSproxy>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  