/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as ierc20Sol from './IERC20.sol/index.js';
export type { ierc20Sol };
import type * as initializableSol from './Initializable.sol/index.js';
export type { initializableSol };
import type * as votingTokenSol from './VotingToken.sol/index.js';
export type { votingTokenSol };
import type * as votingTokenUupSproxySol from './VotingToken_UUPSproxy.sol/index.js';
export type { votingTokenUupSproxySol };
import type * as votingTokenUpgradeableSol from './VotingToken_Upgradeable.sol/index.js';
export type { votingTokenUpgradeableSol };
import type * as votingTokenProxySol from './VotingToken_proxy.sol/index.js';
export type { votingTokenProxySol };
import type * as testHelpers from './test-helpers/index.js';
export type { testHelpers };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { IERC20 } from './IERC20.sol/IERC20.js';
export { IERC20__factory } from './factories/IERC20.sol/IERC20__factory.js';
export type { Initializable } from './Initializable.sol/Initializable.js';
export { Initializable__factory } from './factories/Initializable.sol/Initializable__factory.js';
export type { VotingTokenTest_Upgradeable } from './test-helpers/VotingTokenTest _Upgradeable.sol/VotingTokenTest_Upgradeable.js';
export { VotingTokenTest_Upgradeable__factory } from './factories/test-helpers/VotingTokenTest _Upgradeable.sol/VotingTokenTest_Upgradeable__factory.js';
export type { VotingTokenTest } from './test-helpers/VotingTokenTest.sol/VotingTokenTest.js';
export { VotingTokenTest__factory } from './factories/test-helpers/VotingTokenTest.sol/VotingTokenTest__factory.js';
export type { VotingToken } from './VotingToken.sol/VotingToken.js';
export { VotingToken__factory } from './factories/VotingToken.sol/VotingToken__factory.js';
export type { Proxy } from './VotingToken_proxy.sol/Proxy.js';
export { Proxy__factory } from './factories/VotingToken_proxy.sol/Proxy__factory.js';
export type { VotingToken_Upgradeable } from './VotingToken_Upgradeable.sol/VotingToken_Upgradeable.js';
export { VotingToken_Upgradeable__factory } from './factories/VotingToken_Upgradeable.sol/VotingToken_Upgradeable__factory.js';
export type { VotingToken_UUPSproxy } from './VotingToken_UUPSproxy.sol/VotingToken_UUPSproxy.js';
export { VotingToken_UUPSproxy__factory } from './factories/VotingToken_UUPSproxy.sol/VotingToken_UUPSproxy__factory.js';