/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from './ERC20.sol/index.js';
export type { erc20Sol };
import type * as votingRulesSol from './VotingRules.sol/index.js';
export type { votingRulesSol };
import type * as testHelpers from './test-helpers/index.js';
export type { testHelpers };
export * as factories from './factories/index.js';
export type { ERC20 } from './ERC20.sol/ERC20.js';
export { ERC20__factory } from './factories/ERC20.sol/ERC20__factory.js';
export type { ERC20Test } from './test-helpers/ERC20Test.sol/ERC20Test.js';
export { ERC20Test__factory } from './factories/test-helpers/ERC20Test.sol/ERC20Test__factory.js';
export type { VotingRules } from './VotingRules.sol/VotingRules.js';
export { VotingRules__factory } from './factories/VotingRules.sol/VotingRules__factory.js';